### ISSUE TITLE
'ValueError: No JSON object could be decoded' when running fetch_screenshots 

### ISSUE THREAD

**Issue by bgrins** [mnoorenberghe/mozscreenshots#29]
From https://github.com/mnoorenberghe/mozscreenshots#fetching-images-from-automation:

`fetch_screenshots -r 9f4d4ce255a1` returns 

    Fetching resultset for revision: 9f4d4ce255a1
    Traceback (most recent call last):
      File "/usr/local/bin/fetch_screenshots", line 11, in <module>
        sys.exit(cli())
      File "/usr/local/lib/python2.7/site-packages/mozscreenshots/fetch_screenshots.py", line 199, in cli
        run(args)
      File "/usr/local/lib/python2.7/site-packages/mozscreenshots/fetch_screenshots.py", line 140, in run
        resultset_response = resultset_response_for_push(args.project, args.rev)
      File "/usr/local/lib/python2.7/site-packages/mozscreenshots/fetch_screenshots.py", line 43, in resultset_response_for_push
        response = requests.get(resultset_url).json()
      File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 819, in json
        return json.loads(self.text, **kwargs)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by mnoorenberghe** [comment]
Master didn't have this issue so I released [version 0.4.0](https://github.com/mnoorenberghe/mozscreenshots/releases/tag/0.4.0) and submitted it to pypi. I also added other common examples for fetch_screenshots to the README.

Btw. in the future you can use `--log-level DEBUG` to get more info about the HTTP requests being made.
